### ISSUE TITLE
When starting the app the first time without internet, it crashes

### ISSUE THREAD

**Issue by MarcelGarus** [HPI-de/hpi-flutter#62]
**Describe the bug**
In the `main` method, `await getFont()` is run before the call to `runApp` is made and control is handed to Flutter. When there's no internet, the `await getFont()` fails with a `SocketException` and the app doesn't start.

**Comment by iamprakash13** [comment]
Addressing Issue #62.

**Comment by JonasWanke** [comment]
Closed via #64
