### ISSUE TITLE
Handle unavailable food data

### ISSUE THREAD

**Issue by ctiedt** [HPI-de/hpi-flutter#63]
**Describe the bug**
As the canteen is sometimes closed, there may be no menu data available at times. The app's behaviour is currently undefined in this case. Instead, the app should show that no menu is available.

**Comment by iamprakash13** [comment]
Then you need data of when canteen probably closed. status can be stored as fixed data (like weekends) or make app / service that controls view of menu page of app.(can be controlled by you or hotel). @ctiedt  hope this address the solution you looking for.

**Comment by ctiedt** [comment]
fixed by #60
